# Change listen_port if port 9000 is already in use on your system
# Set listen_to_network to true to make Easy Diffusion accessibble on your local network
net:
  listen_port: 9000
  listen_to_network: true

# Multi GPU setup
render_devices:

# Set open_browser_on_start to false to disable opening a new browser tab on each restart
  - cpu
ui:
  open_browser_on_start: true
update_branch: beta

# Set force_save_path to enforce an auto save path. Clients will not be able to change or
# disable auto save when this option is set. Please adapt the path in the examples to your
# needs.
# Windows:
# force_save_path: C:\\Easy Diffusion Images\\
# Linux:
# force_save_path: /data/easy-diffusion-images/
use_v3_engine: true
models_dir: D:\aianh\models
model:
  stable-diffusion: sd-v1-5
  vae: vae-ft-mse-840000-ema-pruned
vram_usage_level: low
